import { Poppins } from "next/font/google";
import "./globals.css";
import PreloaderHandler from "./PreloaderHandler";
import ConditionalLayout from "./ConditionalLayout";

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${poppins.variable} antialiased`}
        suppressHydrationWarning
      >
        <PreloaderHandler>
          <ConditionalLayout>
            {children}
          </ConditionalLayout>
        </PreloaderHandler>
      </body>
    </html>
  );
}
